import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const domain = 'https://metongroup.com';
const today = '2026-08-13';
const excludedFromSitemap = new Set([
  'account.html',
  'cart.html',
  'compare.html',
  'directus-product.html',
  'equipment-detail.html',
  'product.html',
  // Kept only so old bookmarks do not result in a 404.
  'product-battery-deye-rw-m6.html'
]);

const noindexPages = new Set(excludedFromSitemap);

function escapeJson(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

function stripTags(value) {
  return String(value || '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;|&#160;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function firstMatch(html, expression) {
  const match = html.match(expression);
  return match ? stripTags(match[1]) : '';
}

const catalog = JSON.parse(fs.readFileSync(path.join(root, 'catalog-data.json'), 'utf8'));
const productsByPage = new Map(
  (catalog.products || [])
    .filter((product) => product.page)
    .map((product) => [path.basename(product.page), product])
);

const htmlFiles = fs.readdirSync(root)
  .filter((file) => file.endsWith('.html'))
  .sort((a, b) => a.localeCompare(b));

for (const file of htmlFiles) {
  const fullPath = path.join(root, file);
  let html = fs.readFileSync(fullPath, 'utf8');
  const canonical = file === 'index.html' ? `${domain}/` : `${domain}/${file}`;
  const canonicalTag = `<link rel="canonical" href="${canonical}" />`;

  if (/<link\s+rel=["']canonical["'][^>]*>/i.test(html)) {
    html = html.replace(/<link\s+rel=["']canonical["'][^>]*>/i, canonicalTag);
  } else {
    html = html.replace(/(<meta\s+name=["']robots["'][^>]*>)/i, `$1\n  ${canonicalTag}`);
    if (!html.includes(canonicalTag)) {
      html = html.replace(/<\/head>/i, `  ${canonicalTag}\n</head>`);
    }
  }

  if (noindexPages.has(file)) {
    const robotsTag = '<meta name="robots" content="noindex, follow" />';
    if (/<meta\s+name=["']robots["'][^>]*>/i.test(html)) {
      html = html.replace(/<meta\s+name=["']robots["'][^>]*>/i, robotsTag);
    } else {
      html = html.replace(/<\/head>/i, `  ${robotsTag}\n</head>`);
    }
  }

  // Remove only the schemas generated by this maintenance script. Hand-written
  // Service/CollectionPage schemas on local SEO landing pages remain untouched.
  html = html.replace(/\s*<script type="application\/ld\+json" data-meton-schema="(?:organization|product)">[\s\S]*?<\/script>/gi, '');

  if (file === 'index.html') {
    const organization = {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      '@id': `${domain}/#organization`,
      name: 'METON',
      url: `${domain}/`,
      logo: `${domain}/favicon-512.png`,
      contactPoint: {
        '@type': 'ContactPoint',
        telephone: '+380932852557',
        contactType: 'sales',
        areaServed: 'UA',
        availableLanguage: ['uk']
      },
      sameAs: [
        'https://www.instagram.com/meton.com.ua/',
        'https://www.tiktok.com/@m.e.t.o.n',
        'https://www.youtube.com/@Meton_ua'
      ]
    };
    const schema = `  <script type="application/ld+json" data-meton-schema="organization">${escapeJson(organization)}</script>\n`;
    html = html.replace(/<\/head>/i, `${schema}</head>`);
  }

  if (/^product-.+\.html$/i.test(file)) {
    const product = productsByPage.get(file) || {};
    const title = product.name || firstMatch(html, /<h1[^>]*>([\s\S]*?)<\/h1>/i) || firstMatch(html, /<title[^>]*>([\s\S]*?)<\/title>/i).replace(/\s*\|\s*METON\s*$/i, '');
    const description = product.description || firstMatch(html, /<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i) || firstMatch(html, /<article[^>]*>[\s\S]*?<p[^>]*>([\s\S]*?)<\/p>/i);
    const localImage = product.image || (html.match(/<(?:img)[^>]+src=["']([^"']+)["']/i) || [])[1] || '';
    const brand = product.brand || 'METON';
    const productSchema = {
      '@context': 'https://schema.org',
      '@type': 'Product',
      '@id': `${canonical}#product`,
      name: title,
      description,
      url: canonical,
      image: localImage ? [new URL(localImage, `${domain}/`).href] : undefined,
      brand: { '@type': 'Brand', name: brand }
    };

    const numericPrice = Number(product.price);
    if (Number.isFinite(numericPrice) && numericPrice > 0 && product.currency) {
      productSchema.offers = {
        '@type': 'Offer',
        url: canonical,
        price: numericPrice.toFixed(2),
        priceCurrency: product.currency,
        availability: /під замовлення|preorder/i.test(String(product.availability || ''))
          ? 'https://schema.org/PreOrder'
          : /немає|відсут/i.test(String(product.availability || ''))
            ? 'https://schema.org/OutOfStock'
            : 'https://schema.org/InStock',
        seller: { '@id': `${domain}/#organization` }
      };
    }

    const schema = `  <script type="application/ld+json" data-meton-schema="product">${escapeJson(productSchema)}</script>\n`;
    html = html.replace(/<\/head>/i, `${schema}</head>`);
  }

  fs.writeFileSync(fullPath, html, 'utf8');
}

const sitemapFiles = htmlFiles.filter((file) => {
  if (excludedFromSitemap.has(file)) return false;
  if (/^technical-/i.test(file)) return false;
  return true;
});

function sitemapMeta(file) {
  if (file === 'index.html') return { changefreq: 'weekly', priority: '1.0' };
  if (/^(panels-|inverters-|batteries-|stations-|home\.html|business\.html|credits\.html|sonyachni-)/i.test(file)) return { changefreq: 'weekly', priority: '0.9' };
  if (/^product-/i.test(file)) return { changefreq: 'weekly', priority: '0.8' };
  if (/^blog/i.test(file)) return { changefreq: 'monthly', priority: '0.7' };
  if (/^(passport-|consultation\.html)/i.test(file)) return { changefreq: 'monthly', priority: '0.5' };
  return { changefreq: 'monthly', priority: '0.7' };
}

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...sitemapFiles.map((file) => {
    const { changefreq, priority } = sitemapMeta(file);
    const loc = file === 'index.html' ? `${domain}/` : `${domain}/${file}`;
    return `  <url><loc>${loc}</loc><lastmod>${today}</lastmod><changefreq>${changefreq}</changefreq><priority>${priority}</priority></url>`;
  }),
  '</urlset>',
  ''
].join('\n');

fs.writeFileSync(path.join(root, 'sitemap.xml'), sitemap, 'utf8');
console.log(`SEO updated: ${htmlFiles.length} canonical URLs, ${productsByPage.size} catalogue product schemas, ${sitemapFiles.length} sitemap URLs.`);
